eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 5

spring:
  cloud:
    gateway:
      routes:
        - id: nuevo-microservicio
          uri: lb://nuevo-microservicio
          predicates:
            - Path=/nuevo-microservicio/**